included:
  - Targets
excluded:
  - Carthage
  - Pods
  - Frameworks
  - build
  - Tuist
  - Derived/*
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - identifier_name
  - trailing_comma
  - force_try
line_length: 180