#!/bin/sh

set -eu

mkdir -p .git/hooks

move_hook() {
    name=$1
    echo "Installing $name Hook"
    file=".git/hooks/$name"
    rm -f $file
    cp -f Tools/scripts/hooks/$name $file
}

move_hook pre-commit
move_hook commit-msg
move_hook pre-push

which -s brew
if [ $? != 0 ] ; then
    ruby -e "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
fi

brew_install() {
    echo "\nInstalling $1"
    if brew list $1 &>/dev/null; then
        echo "${1} is already installed"
    else
        brew install $1 && echo "$1 is installed"
    fi
}

brew_install "swiftlint"
brew_install "swiftformat"
brew_install "xcbeautify"
brew_install "carthage"
# brew_install "cocoapods"

which -s tuist
if [ $? != 0 ]; then
    curl -Ls https://install.tuist.io | bash
fi

tuist fetch
tuist generate
# pod install
