#!/bin/sh

echo "Running pre-commit Hook"

ignoreHeader(){
    output=$($PWD/Tools/scripts/git-format-staged --formatter "swiftformat stdin --config .swiftformat --header ignore --stdinpath {}" "**/Package.swift" 2>&1)
    if [ $? -eq 1 ]
    then
        echo "$output"
    fi
}

excludeFile() {
    output=$($PWD/Tools/scripts/git-format-staged --formatter "swiftformat stdin --config .swiftformat --stdinpath {}" "*.swift" "!**/Package.swift" 2>&1)
    if [ $? -eq 1 ]
    then
        echo "$output"
    fi
}

which -s swiftformat
if [ $? != 0 ] ; then
    echo "❌ swiftformat is not installed"
    exit 0
fi

echo "Swiftformat started..."
ignoreHeader
excludeFile
echo "✅ Swiftformat finished"

which -s swiftlint
if [ $? != 0 ] ; then
    echo "❌ swiftlint is not installed"
    exit 0
fi

echo "Swiftlint started..."
swiftlint --quiet --config .swiftlint.yml --strict

if [ $? -ne 0 ]; then
    echo "❌ Swiftlint finished with errors"
    exit 1
fi

echo "✅ Swiftlint finished"

# exit 1